import { basename } from 'node:path';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ConsoleRenderer } from './ConsoleRenderer.js';
import { detectProjectContext, type ProjectContext } from '../agent/ProjectContext.js';

const FILE_NAME = 'AUTOCODE.md';

export async function runInit(projectRoot: string, renderer: ConsoleRenderer): Promise<void> {
  const target = join(projectRoot, FILE_NAME);
  if (existsSync(target)) {
    renderer.error(`${FILE_NAME} already exists at ${target}.`);
    renderer.dim(`Delete it first if you want to regenerate, or edit it directly.`);
    return;
  }
  const ctx = detectProjectContext(projectRoot);
  const projectName = inferProjectName(projectRoot);
  const content = renderTemplate(projectName, ctx);
  writeFileSync(target, content, 'utf8');
  renderer.info(`✓ Created ${FILE_NAME} at ${target}`);
  renderer.dim(`Edit it to encode your project's conventions, then /exit and relaunch to load.`);
}

export function renderTemplate(projectName: string, ctx: ProjectContext): string {
  const date = new Date().toISOString().slice(0, 10);
  const types = ctx.types.length > 0 ? ctx.types.join(', ') : '(none detected)';
  const verify = inferVerifyCommand(ctx.types) ?? '(add your project\'s test or build command here)';
  return `<!-- Generated by autocode /init on ${date}. Edit freely. -->
# Project: ${projectName}

(One-line description of this project goes here.)

## Conventions

- Language(s): ${types}
- Indentation: (e.g. 2 spaces, tabs)
- Naming: (e.g. snake_case for files, camelCase for variables)
- Imports: (e.g. relative paths, type-only imports use \`import type\`)
- Quotes: (e.g. single quotes for strings, backticks for templates)

## Architecture

(Brief description of the high-level shape of the codebase: which folders
do what, where the entrypoints are, what the major modules are.)

## Working principles

- After non-trivial code changes, run: \`${verify}\`
- Prefer small, exact edits over full-file rewrites.
- Don't add dependencies casually — explain the tradeoff first.
- (Add project-specific rules here.)

## Out of bounds

(Files, folders, or commands the agent should never touch in this project.)
`;
}

function inferProjectName(root: string): string {
  const pkgPath = join(root, 'package.json');
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { name?: string };
      if (typeof pkg.name === 'string' && pkg.name.length > 0) return pkg.name;
    } catch {
      /* fall through */
    }
  }
  const base = basename(root);
  return base.length > 0 ? base : 'this-project';
}

function inferVerifyCommand(types: readonly string[]): string | null {
  if (types.includes('node') || types.includes('typescript')) return 'npm test';
  if (types.includes('python')) return 'pytest';
  if (types.includes('rust')) return 'cargo test';
  if (types.includes('go')) return 'go test ./...';
  if (types.includes('dotnet')) return 'dotnet test';
  if (types.includes('ruby')) return 'bundle exec rspec';
  if (types.includes('jvm')) return 'mvn test';
  if (types.includes('elixir')) return 'mix test';
  return null;
}
