import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { runInit, renderTemplate } from '../../src/repl/InitCommand.js';
import type { ConsoleRenderer } from '../../src/repl/ConsoleRenderer.js';

function mockRenderer(): { renderer: ConsoleRenderer; info: string[]; error: string[]; dim: string[] } {
  const info: string[] = [];
  const error: string[] = [];
  const dim: string[] = [];
  const renderer = {
    info: (t: string) => info.push(t),
    error: (t: string) => error.push(t),
    dim: (t: string) => dim.push(t),
  } as unknown as ConsoleRenderer;
  return { renderer, info, error, dim };
}

describe('renderTemplate', () => {
  it('includes the project name in the heading', () => {
    const out = renderTemplate('my-app', { root: '/x', types: ['node'], git: null });
    expect(out).toMatch(/^# Project: my-app/m);
  });

  it('lists detected types in the Conventions section', () => {
    const out = renderTemplate('x', { root: '/x', types: ['typescript', 'python'], git: null });
    expect(out).toMatch(/Language\(s\): typescript, python/);
  });

  it('shows a sensible verify command per ecosystem', () => {
    const node = renderTemplate('x', { root: '/x', types: ['node'], git: null });
    expect(node).toMatch(/npm test/);
    const rust = renderTemplate('x', { root: '/x', types: ['rust'], git: null });
    expect(rust).toMatch(/cargo test/);
    const py = renderTemplate('x', { root: '/x', types: ['python'], git: null });
    expect(py).toMatch(/pytest/);
  });

  it('falls back gracefully when no types are detected', () => {
    const out = renderTemplate('x', { root: '/x', types: [], git: null });
    expect(out).toMatch(/Language\(s\): \(none detected\)/);
    expect(out).toMatch(/add your project's test or build command/);
  });

  it('starts with a marker comment so users know it was generated', () => {
    const out = renderTemplate('x', { root: '/x', types: [], git: null });
    expect(out.startsWith('<!-- Generated by autocode /init')).toBe(true);
  });
});

describe('runInit', () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'autocode-init-'));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('creates AUTOCODE.md in a fresh directory', async () => {
    const { renderer, info } = mockRenderer();
    await runInit(dir, renderer);
    const path = join(dir, 'AUTOCODE.md');
    expect(existsSync(path)).toBe(true);
    const content = readFileSync(path, 'utf8');
    expect(content).toMatch(/^# Project:/m);
    expect(info.some((l) => l.includes('Created AUTOCODE.md'))).toBe(true);
  });

  it('refuses when AUTOCODE.md already exists', async () => {
    writeFileSync(join(dir, 'AUTOCODE.md'), 'pre-existing');
    const { renderer, error, info } = mockRenderer();
    await runInit(dir, renderer);
    expect(error.some((l) => l.includes('already exists'))).toBe(true);
    expect(info).toHaveLength(0);
    // File contents preserved (not overwritten).
    expect(readFileSync(join(dir, 'AUTOCODE.md'), 'utf8')).toBe('pre-existing');
  });

  it('picks up the project name from package.json', async () => {
    writeFileSync(join(dir, 'package.json'), '{"name": "fancy-pkg"}');
    const { renderer } = mockRenderer();
    await runInit(dir, renderer);
    const content = readFileSync(join(dir, 'AUTOCODE.md'), 'utf8');
    expect(content).toMatch(/# Project: fancy-pkg/);
  });
});
